development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: totem_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: totem_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: totem_prod
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock